/**
* Site Configuration
* Generated by Netlify Function
* Last updated: 2025-10-21T18:37:51.434Z
*/

// contactInfo configuration
export const contactInfo = {
    agent: {
      name: "Tom Storey",
      photo: "https://storeyteam.ca/uploads/2023/09/portrait-short-tom-2-960x1200.webp",
      phone: "4166702432",
      email: "tom@storeyteam.ca",
      company: "Royal LePage Signature",
      license: "REALTOR",
      repo: "New-Listing-4",
      companyAddress: "495 Wellington St. W #100",
      companyLogo: "https://i.imgur.com/lKIbLxJ.png"
    },
    social: {
      instagram: "https://instagram.com/thestoreyteam",
      facebook: "https://facebook.com/thestoreyteam",
      twitter: "https://twitter.com/executivehomesrealtyinc",
      linkedin: ""
    },
    email: "tom@storeyteam.ca",
    phone: "4166702432",
    address: "495 Wellington St. W #100",
    hours: "Mon-Fri: 9am-5pm",
    mapLocation: {
      lat: 43.7,
      lng: -79.4
    },
    socialLinks: {
      instagram: "https://instagram.com/thestoreyteam",
      facebook: "https://facebook.com/executivehomesrealtyinc",
      twitter: "https://twitter.com/executivehomesrealtyinc",
      linkedin: "https://linkedin.com/company/executivehomesrealtyinc"
    },
    agent2: null
  };

// galleryImages configuration
export const galleryImages = [
    {
      id: 1,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989337789-151 Eastwood Avenue-1.jpg",
      alt: "Property image 1",
      category: "interior"
    },
    {
      id: 2,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989338033-151 Eastwood Avenue-2.jpg",
      alt: "Property image 2",
      category: "kitchen"
    },
    {
      id: 3,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989338200-151 Eastwood Avenue-3.jpg",
      alt: "Property image 3",
      category: "bedroom"
    },
    {
      id: 4,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989338335-151 Eastwood Avenue-4.jpg",
      alt: "Property image 4",
      category: "bathroom"
    },
    {
      id: 5,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989338495-151 Eastwood Avenue-5.jpg",
      alt: "Property image 5",
      category: "exterior"
    },
    {
      id: 6,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989338668-151 Eastwood Avenue-6.jpg",
      alt: "Property image 6",
      category: "interior"
    },
    {
      id: 7,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989338809-151 Eastwood Avenue-7.jpg",
      alt: "Property image 7",
      category: "kitchen"
    },
    {
      id: 8,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989338949-151 Eastwood Avenue-8.jpg",
      alt: "Property image 8",
      category: "bedroom"
    },
    {
      id: 9,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989339121-151 Eastwood Avenue-9.jpg",
      alt: "Property image 9",
      category: "bathroom"
    },
    {
      id: 10,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989339263-151 Eastwood Avenue-10.jpg",
      alt: "Property image 10",
      category: "exterior"
    },
    {
      id: 11,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989339444-151 Eastwood Avenue-11.jpg",
      alt: "Property image 11",
      category: "interior"
    },
    {
      id: 12,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989339555-151 Eastwood Avenue-12.jpg",
      alt: "Property image 12",
      category: "kitchen"
    },
    {
      id: 13,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989339682-151 Eastwood Avenue-13.jpg",
      alt: "Property image 13",
      category: "bedroom"
    },
    {
      id: 14,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989339845-151 Eastwood Avenue-14.jpg",
      alt: "Property image 14",
      category: "bathroom"
    },
    {
      id: 15,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989340014-151 Eastwood Avenue-15.jpg",
      alt: "Property image 15",
      category: "exterior"
    },
    {
      id: 16,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989340155-151 Eastwood Avenue-16.jpg",
      alt: "Property image 16",
      category: "interior"
    },
    {
      id: 17,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989340319-151 Eastwood Avenue-17.jpg",
      alt: "Property image 17",
      category: "kitchen"
    },
    {
      id: 18,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989340506-151 Eastwood Avenue-18.jpg",
      alt: "Property image 18",
      category: "bedroom"
    },
    {
      id: 19,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989340676-151 Eastwood Avenue-19.jpg",
      alt: "Property image 19",
      category: "bathroom"
    },
    {
      id: 20,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989340858-151 Eastwood Avenue-20.jpg",
      alt: "Property image 20",
      category: "exterior"
    },
    {
      id: 21,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989341035-151 Eastwood Avenue-21.jpg",
      alt: "Property image 21",
      category: "interior"
    },
    {
      id: 22,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989341201-151 Eastwood Avenue-22.jpg",
      alt: "Property image 22",
      category: "kitchen"
    },
    {
      id: 23,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989341408-151 Eastwood Avenue-23.jpg",
      alt: "Property image 23",
      category: "bedroom"
    },
    {
      id: 24,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989341590-151 Eastwood Avenue-24.jpg",
      alt: "Property image 24",
      category: "bathroom"
    },
    {
      id: 25,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989341718-151 Eastwood Avenue-25.jpg",
      alt: "Property image 25",
      category: "exterior"
    },
    {
      id: 26,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989341887-151 Eastwood Avenue-26.jpg",
      alt: "Property image 26",
      category: "interior"
    },
    {
      id: 27,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989342024-151 Eastwood Avenue-27.jpg",
      alt: "Property image 27",
      category: "kitchen"
    },
    {
      id: 28,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989342134-151 Eastwood Avenue-28.jpg",
      alt: "Property image 28",
      category: "bedroom"
    },
    {
      id: 29,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989342279-151 Eastwood Avenue-29.jpg",
      alt: "Property image 29",
      category: "bathroom"
    },
    {
      id: 30,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989342444-151 Eastwood Avenue-30.jpg",
      alt: "Property image 30",
      category: "exterior"
    },
    {
      id: 31,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989342612-151 Eastwood Avenue-31.jpg",
      alt: "Property image 31",
      category: "interior"
    },
    {
      id: 32,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989342801-151 Eastwood Avenue-32.jpg",
      alt: "Property image 32",
      category: "kitchen"
    },
    {
      id: 33,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989343013-151 Eastwood Avenue-33.jpg",
      alt: "Property image 33",
      category: "bedroom"
    },
    {
      id: 34,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989343212-151 Eastwood Avenue-34.jpg",
      alt: "Property image 34",
      category: "bathroom"
    },
    {
      id: 35,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989343385-151 Eastwood Avenue-35.jpg",
      alt: "Property image 35",
      category: "exterior"
    },
    {
      id: 36,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989343544-151 Eastwood Avenue-36.jpg",
      alt: "Property image 36",
      category: "interior"
    },
    {
      id: 37,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989343717-151 Eastwood Avenue-37.jpg",
      alt: "Property image 37",
      category: "kitchen"
    },
    {
      id: 38,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989343881-151 Eastwood Avenue-38.jpg",
      alt: "Property image 38",
      category: "bedroom"
    },
    {
      id: 39,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989344033-151 Eastwood Avenue-39.jpg",
      alt: "Property image 39",
      category: "bathroom"
    },
    {
      id: 40,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989344200-151 Eastwood Avenue-40.jpg",
      alt: "Property image 40",
      category: "exterior"
    },
    {
      id: 41,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989344396-151 Eastwood Avenue-41.jpg",
      alt: "Property image 41",
      category: "interior"
    },
    {
      id: 42,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989344623-151 Eastwood Avenue-42.jpg",
      alt: "Property image 42",
      category: "kitchen"
    },
    {
      id: 43,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989344785-151 Eastwood Avenue-43.jpg",
      alt: "Property image 43",
      category: "bedroom"
    },
    {
      id: 44,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989344940-151 Eastwood Avenue-44.jpg",
      alt: "Property image 44",
      category: "bathroom"
    },
    {
      id: 45,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989345088-151 Eastwood Avenue-45.jpg",
      alt: "Property image 45",
      category: "exterior"
    },
    {
      id: 46,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989345257-151 Eastwood Avenue-46.jpg",
      alt: "Property image 46",
      category: "interior"
    },
    {
      id: 47,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989345476-151 Eastwood Avenue-47.jpg",
      alt: "Property image 47",
      category: "kitchen"
    },
    {
      id: 48,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989345607-151 Eastwood Avenue-48.jpg",
      alt: "Property image 48",
      category: "bedroom"
    },
    {
      id: 49,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989345751-151 Eastwood Avenue-49.jpg",
      alt: "Property image 49",
      category: "bathroom"
    },
    {
      id: 50,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989345895-151 Eastwood Avenue-50.jpg",
      alt: "Property image 50",
      category: "exterior"
    },
    {
      id: 51,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989346046-151 Eastwood Avenue-51.jpg",
      alt: "Property image 51",
      category: "interior"
    },
    {
      id: 52,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989346191-151 Eastwood Avenue-52.jpg",
      alt: "Property image 52",
      category: "kitchen"
    },
    {
      id: 53,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989346325-151 Eastwood Avenue-53.jpg",
      alt: "Property image 53",
      category: "bedroom"
    },
    {
      id: 54,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989346500-151 Eastwood Avenue-54.jpg",
      alt: "Property image 54",
      category: "bathroom"
    },
    {
      id: 55,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989346670-151 Eastwood Avenue-55.jpg",
      alt: "Property image 55",
      category: "exterior"
    },
    {
      id: 56,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989346800-151 Eastwood Avenue-56.jpg",
      alt: "Property image 56",
      category: "interior"
    },
    {
      id: 57,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989346927-151 Eastwood Avenue-57.jpg",
      alt: "Property image 57",
      category: "kitchen"
    },
    {
      id: 58,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989347084-151 Eastwood Avenue-58.jpg",
      alt: "Property image 58",
      category: "bedroom"
    },
    {
      id: 59,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989347250-151 Eastwood Avenue-59.jpg",
      alt: "Property image 59",
      category: "bathroom"
    },
    {
      id: 60,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989347451-151 Eastwood Avenue-60.jpg",
      alt: "Property image 60",
      category: "exterior"
    },
    {
      id: 61,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989347621-151 Eastwood Avenue-61.jpg",
      alt: "Property image 61",
      category: "interior"
    },
    {
      id: 62,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989347796-151 Eastwood Avenue-62.jpg",
      alt: "Property image 62",
      category: "kitchen"
    },
    {
      id: 63,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989347929-151 Eastwood Avenue-63.jpg",
      alt: "Property image 63",
      category: "bedroom"
    },
    {
      id: 64,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989348087-151 Eastwood Avenue-64.jpg",
      alt: "Property image 64",
      category: "bathroom"
    },
    {
      id: 65,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989348462-151 Eastwood Avenue-65.jpg",
      alt: "Property image 65",
      category: "exterior"
    },
    {
      id: 66,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989348650-151 Eastwood Avenue-66.jpg",
      alt: "Property image 66",
      category: "interior"
    },
    {
      id: 67,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989348804-151 Eastwood Avenue-67.jpg",
      alt: "Property image 67",
      category: "kitchen"
    },
    {
      id: 68,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989348990-151 Eastwood Avenue-68.jpg",
      alt: "Property image 68",
      category: "bedroom"
    },
    {
      id: 69,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989349119-151 Eastwood Avenue-69.jpg",
      alt: "Property image 69",
      category: "bathroom"
    },
    {
      id: 70,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989349275-151 Eastwood Avenue-70.jpg",
      alt: "Property image 70",
      category: "exterior"
    }
  ];

// heroVideo configuration
export const heroVideo = {
    url: "https://www.instagram.com/p/DP38ovZjjy9/",
    type: "video/mp4",
    autoplay: true,
    loop: true,
    muted: true,
    playsInline: true
  };

// homeShowcaseSections configuration
export const homeShowcaseSections = [
    {
      id: "section1",
      title: "3 Bedrooms",
      description: "Bright and open ",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989337789-151 Eastwood Avenue-1.jpg"
    },
    {
      id: "section2",
      title: "2.5 Bathrooms",
      description: "",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989338033-151 Eastwood Avenue-2.jpg"
    },
    {
      id: "section3",
      title: "1400 SqFt",
      description: "Spacious living area with ample room for your lifestyle",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989338200-151 Eastwood Avenue-3.jpg"
    },
    {
      id: "section4",
      title: "$$1,265,000",
      description: "",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989338335-151 Eastwood Avenue-4.jpg"
    }
  ];

// neighborhood configuration
export const neighborhood = {
    name: "Birchcliffe-Cliffside",
    city: "Toronto",
    description: "Birchcliffe-Cliffside is an East Toronto lakeside neighbourhood known for family-friendly beaches, quiet residential streets and easy access to parks and local eateries. Residents enjoy a multicultural dining scene along Kingston Road and Danforth, plus nearby green spaces like Eastwood Park and scenic cliff-top views toward Lake Ontario.",
    highlights: [
      "Woodbine Beach — family favorite for sand, water sports, and a lakeside boardwalk",
      "Eastwood Park — local green space with playgrounds, sports fields, and picnic amenities",
      "Vibrant multicultural dining — easy access to authentic Greek, Indian and Caribbean flavours",
      "Proximity to historic Eastwood Theater — local landmark in a walkable area",
      "Quiet, family-friendly streets with quick routes to lakeside trails and parks"
    ]
  };

// neighborhoodAmenities configuration
export const neighborhoodAmenities = [
    {
      id: 1,
      name: "Tony & Claudia's on Fallingbrook (Italian grocery)",
      distance: "",
      category: "shopping",
      iconName: "ShoppingBag"
    },
    {
      id: 2,
      name: "Birchmount Park",
      distance: "",
      category: "recreation",
      iconName: "Leaf"
    },
    {
      id: 3,
      name: "Little Canada (interactive miniature attraction)",
      distance: "",
      category: "education",
      iconName: "School"
    },
    {
      id: 4,
      name: "The Jalsa Indian Cuisine | Bar + Indian Kitchen",
      distance: "",
      category: "dining",
      iconName: "Coffee"
    },
    {
      id: 5,
      name: "Delina Restaurant",
      distance: "",
      category: "dining",
      iconName: "Utensils"
    },
    {
      id: 6,
      name: "Danforth Ave at Eastwood Ave (bus stop)",
      distance: "",
      category: "transportation",
      iconName: "Car"
    },
    {
      id: 7,
      name: "Scarborough Heights Park",
      distance: "",
      category: "recreation",
      iconName: "Users"
    },
    {
      id: 8,
      name: "Toronto Transit Commission - Birchmount Garage",
      distance: "",
      category: "business",
      iconName: "Wifi"
    }
  ];

// neighborhoodStats configuration
export const neighborhoodStats = [
    {
      id: 1,
      title: "Walk Score",
      value: "74/100",
      caption: "Very Walkable",
      iconName: "BadgeCheck",
      color: "bg-green-500"
    },
    {
      id: 2,
      title: "Transit Score",
      value: "69/100",
      caption: "Good Transit",
      iconName: "Compass",
      color: "bg-blue-500"
    },
    {
      id: 3,
      title: "Bike Score",
      value: "68/100",
      caption: "Good for Bikers",
      iconName: "Bicycle",
      color: "bg-indigo-500"
    }
  ];

// openHouseBenefits configuration
export const openHouseBenefits = [
    {
      id: 1,
      title: "Detailed Floor Plans",
      description: "Complete architectural layouts showing the 3 bedroom, 2.5 bathroom configuration with precise measurements.",
      iconName: "FileText"
    },
    {
      id: 2,
      title: "Recent Neighborhood Sales",
      description: "Comparative market analysis of recent Detached sales in Toronto.",
      iconName: "BarChart2"
    },
    {
      id: 3,
      title: "School District Information",
      description: "N/A",
      iconName: "GraduationCap"
    },
    {
      id: 4,
      title: "Property Inspection Report",
      description: "Professional assessment highlighting recent upgrades and maintenance history.",
      iconName: "CheckSquare"
    },
    {
      id: 5,
      title: "Financing Options Guide",
      description: "Current mortgage rates and financing programs available for this price range.",
      iconName: "DollarSign"
    },
    {
      id: 6,
      title: "Neighborhood Amenities Map",
      description: "Interactive guide to nearby amenities and transportation options.",
      iconName: "Map"
    }
  ];

// openHouseDetails configuration
export const openHouseDetails = {
    nextDate: "Monday, October 27, 2025",
    time: "2:00 PM - 4:00 PM",
    host: "Tom",
    phone: "4166702432",
    email: "tom@storeyteam.ca",
    ctaText: "RSVP for Open House",
    virtualTourAvailable: false,
    virtualTourUrl: "",
    allOpenHouses: [
      {
        date: "Monday, October 27, 2025",
        time: "2:00 PM - 4:00 PM"
      }
    ],
    date: "",
    startTime: "",
    endTime: "",
    location: "",
    registerLink: "#"
  };

// packageItems configuration
export const packageItems = [
    {
      id: 1,
      title: "Detailed Floor Plans",
      description: "Complete architectural layouts showing the 3 bedroom, 2.5 bathroom configuration with precise measurements.",
      iconName: "FileText"
    },
    {
      id: 2,
      title: "Recent Neighborhood Sales",
      description: "Comparative market analysis of recent Detached sales in Toronto.",
      iconName: "BarChart2"
    },
    {
      id: 3,
      title: "School District Information",
      description: "N/A",
      iconName: "GraduationCap"
    },
    {
      id: 4,
      title: "Property Inspection Report",
      description: "Professional assessment highlighting recent upgrades and maintenance history.",
      iconName: "CheckSquare"
    },
    {
      id: 5,
      title: "Financing Options Guide",
      description: "Current mortgage rates and financing programs available for this price range.",
      iconName: "DollarSign"
    },
    {
      id: 6,
      title: "Neighborhood Amenities Map",
      description: "Interactive guide to nearby amenities and transportation options.",
      iconName: "Map"
    }
  ];

// property configuration
export const property = {
    name: "151 Eastwood Avenue",
    address: {
      street: "151 Eastwood Avenue",
      city: "Toronto",
      state: "Ontario",
      zip: "M1N 3H5",
      country: "Canada"
    },
    price: "$1,265,000",
    beds: 3,
    baths: 2.5,
    sqft: 1400,
    lotSize: "30 x 120 ft",
    yearBuilt: 2010,
    type: "Detached",
    status: "For Sale",
    description: "Move in ready ",
    shortDescription: "3 BEDS + 3 BATHS in Toronto",
    longDescription: "Large backyard  Recently Renovated  Detached",
    mainFeatures: [],
    propertyType: "Detached",
    heroImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989337789-151 Eastwood Avenue-1.jpg",
    heroCaption: "Large Backyard + Recently Renovated + 3-Car Parking = Your Perfect Family Home Just Listed!"
  };

// propertyFeatures configuration
export const propertyFeatures = [
    "Size of the backyard",
    "3 car parking pad"
  ];

// siteBranding configuration
export const siteBranding = {
    logoUrl: "https://i.imgur.com/lKIbLxJ.png",
    logoAlt: "151 Eastwood Avenue",
    favicon: "/favicon.ico",
    colors: {
      primary: "#D9A566",
      primaryDark: "#8B6839",
      primaryLight: "#E6C38C",
      dark: "#111111",
      light: "#FFFFFF"
    },
    heroImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989337789-151 Eastwood Avenue-1.jpg",
    footer: {
      copyrightText: "© 2024 151 Eastwood Avenue. All rights reserved.",
      disclaimer: "This website is for informational purposes only. Details are subject to change."
    },
    companyName: "Royal LePage Signature",
    companyLogo: "https://i.imgur.com/lKIbLxJ.png",
    accentColor: "#D9A566",
    footerText: "© 2024 151 Eastwood Avenue. All rights reserved."
  };

// siteMetadata configuration
export const siteMetadata = {
    title: "151 Eastwood Avenue | Detached | Toronto",
    description: "Large Backyard + Recently Renovated + 3-Car Parking = Your Perfect Family Home Just Listed!",
    keywords: "detached, Toronto real estate, 3 bedroom, 2.5 bathroom, $1,265,000",
    ogImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989337789-151 Eastwood Avenue-1.jpg",
    ogType: "website",
    twitterCard: "summary_large_image",
    canonical: "https://151eastwoodavenue.com"
  };

// testimonials configuration
export const testimonials = [
    {
      id: 1,
      name: "David Chen",
      role: "Recent Homebuyer",
      content: "Tom provided exceptional service and found us exactly what we were looking for in Toronto.",
      avatar: "https://randomuser.me/api/portraits/men/22.jpg"
    },
    {
      id: 2,
      name: "Jennifer Liu",
      role: "Interior Designer",
      content: "The attention to detail and quality of finishes in this property is outstanding. Tom presented every detail clearly.",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg"
    },
    {
      id: 3,
      name: "Mark Williams",
      role: "Neighborhood Resident",
      content: "Living in this area, you appreciate the convenience and lifestyle. Tom knows the market incredibly well.",
      avatar: "https://randomuser.me/api/portraits/men/35.jpg"
    }
  ];

